# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dbc12f8c9c4db8cf20930fc4fa4150a53d8fa6389bc5c493a83820599862ec32a0e03353f762452cf7a9c0669ae11bc7800e082167e25c34b9e4a1c0ec2fbbb

test:
  secret_key_base: 47388e3cd77ecd0f4511a4da7d42d817e36d1841e21179db29a6119b1dce88f7923db1ea97ae3716d4d22ab2694f0ffdeb396d526f5cd45c61cf90f2ac769ba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
